language: php

php:
  - '7.0'

services:
  - mysql

env:
  - GOTEO_CONFIG_FILE="$TRAVIS_BUILD_DIR/config/travis-settings.yml"

before_script:
  - mysql -e 'CREATE DATABASE goteo;'
  - composer install
  - ./bin/console migrate install

script:
  - ./run-tests.sh -t config/travis-settings.yml tests/
