language: php

php:
  - '5.6'
  - '7.0'

services:
  - mysql

env:
  - GOTEO_CONFIG_FILE="$TRAVIS_BUILD_DIR/config/vagrant-settings.yml"

before_script:
  - mysql -e 'create database goteo;'
  - mysql -e 'create database goteo;'
  - mysql -e "GRANT ALL PRIVILEGES ON goteo TO 'root'@'%' IDENTIFIED BY 'root';"
  - composer self-update
  - composer install
  - ./bin/console migrate install

script:
  - ./run-tests.sh -t config/vagrant-settings.yml tests/
